### ISSUE TITLE
vim TeXpresso cannot excutable

### ISSUE THREAD

**Issue by D-Simpackuser** [let-def/texpresso.vim#3]
Error executing Lua callback: Vim:E475: Invalid value for argument cmd: 'texpresso' is not executable                                           
stack traceback:
        [C]: in function 'jobstart'
        /home/d/.config/nvim/start/texpresso.vim/lua/texpresso.lua:306: in function 'launch'
        /home/d/.config/nvim/start/texpresso.vim/lua/texpresso.lua:353: in function </home/d/.config/nvim/start/texpresso.vim/lua/texpresso.lua:352>

**Comment by let-def** [comment]
The texpresso binary (from https://github.com/let-def/texpresso) needs to be visible in PATH for vim to execute it.

Alternatively, I just added a customization option to specify a different path: [README.md#texpresso_path](https://github.com/let-def/texpresso.vim/blob/1cc949fde8ed3220968039b6b1b6ccdd9f475087/README.md#texpresso_path).
